# Generated by Django 3.0.9 on 2020-08-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={},
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='temperature',
        ),
        migrations.AddField(
            model_name='forecast',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
